### PR TITLE
Send stdout to /dev/null unless it is needed

### PR DESCRIPTION
**Pull request by ChrisJefferson**
'unrar' produces lots of output to stdout, and previously this output was stored in a pipe with Subprocess.PIPE, which could get filled up, causing everything to hang.

Almost all the of the time we do not care what uncompressors are producing on stdout, so just send it to /dev/null. Add a way of stopping this behaviour for the one uncompressor which currently does read the output pipe.

### CODE REVIEW

**Comment by petoor** [comment]
hi @noahp.

I need this PR. Would you be kind as to either accept it or reject it?

**Comment by petoor** [comment]
@noahp any chance you could accept / reject this?

**Comment by noahp** [comment]
@petoor apologies, just seeing this, thank you for the notification! Merging now.

**Comment by noahp** [comment]
Published this in 8.5.3.

**Comment by petoor** [comment]
Cheers!

**Pull request merged**
